baseURL = "https://amplify-workshop.go-aws.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amplify / AppSync / React Workshop"
theme = "learn"
uglyurls = true
#googleAnalytics = "UA-129511631-1"
sectionPagesMenu = "main"
pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true
#pygmentsStyle = "monokai"


[blackfriday]
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe = true # Optional, allows HTML inside your CommonMark content


[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Gabe Hollombe"
description = "Amplify / AppSync / React Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true


# [menu]
#   [[menu.main]]
#     identifier = "Prerequisites"
#     name = "This is the Mu track"
#     title = "Workshop using Mu"
#     url = "/mu/"
#     weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @gabehollombe"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=gabehollombe"
weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
